## 通过异常处理错误

### 概念
如果当前环境无法获得必要的信息来解决问题，你所能做的就是从当前环境中跳出，并且把问题交给上一级环境。

    当抛出异常后，有几件事会随之发生，首先，同Java中其他对象的创建一样，将使用new在对上创建异常对象。然后当前的执行路径被终止，并且从当前环境中弹出对异常对象的应用。此时，异常处理及直接管程序，并开始寻找一个恰当的地方来继续执行程序，而这个恰当的地方就是 <font color=orange>``异常处理程序``</font>

### 使用情况

异常处理机制使用原理：如果发生问题在没有其他手段情况下异常允许我们强制停止程序并告诉我们出现了什么问题，并返回到稳定的状态，不同于事务回滚。即对于不确定的代码使用try括起来并再catch中尝试修复然后继续执行后续代码，例如如果数据错误尝试给定默认值并给出提示信息。如果不能给定默认值的情况发生则向上抛出交由调用方处理。

### try-catch和throw，throws区别

throw 就是抛出一个异常并获取这个异常的引用。在方法中使用。一般和throws搭配用在写基础工具类或者接口(方法被别人调用)中使用。为什么要和throws使用呢？

throws 就是一个异常声明：表明该方法有可能抛出异常来提高代码的健壮性。因此在方法体中使用。当代码中有throw抛出异常则编辑器规范要在该方法体中申明。

try-catch 用来处理异常的代码语句。在方法中使用。一般用在方法调用者中使用也就是相对上层方法调用者或者是controller中。因为在controller一般方法都和页面请求打交道如果你此刻还抛出异常则没有人去处理，则在页面中直接反馈错误信息，体验及其不良好。如果你需要在发生异常代码处继续执行往下代码或者是恢复修改的数据又或者是关闭文件、关闭网络连接、关闭数据库连接等，则你可以在catch中或者finally纠正错误并继续执行


### 栈轨迹

printStackTrace()方法所提供的信息可以通过getStackTrace()来直接访问，<font color=#ad6800>这个方法将返回一个由栈轨迹中的元素所构成的数组，其中每一个元素都表示栈中的一帧。元素0是栈顶元素也是最后一个方法调用。因此在控制台输出中从上往下是出现异常的方法调用链。</font>

```java
package exception;

/**
 * TODO:<p>  异常调用栈以及丢失原来的异常信息并生成与新抛出点有关的信息<p/>
 *
 * @package: exception
 * @Author mac
 * @Date 2020/2/24 9:29 下午
 * @Version V1.0
 **/
public class Rethrowing {
    public static void main(String[] args) {
        Rethrowing te = new Rethrowing();

        try{
            te.f1();
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    void f1() throws Exception{
        try{
            f2();
        }catch(Exception e){
            e.printStackTrace();
//            e.fillInStackTrace();
            throw e;
        }
    }

    void f2() throws Exception{
        try{
            f3();
        }catch(Exception e){
            e.printStackTrace();
            e.fillInStackTrace();
            throw e;
        }
    }
    void f3()throws Exception{
        throw new Exception();
    }
}
```
如果不把代码中一行注释掉则三处```e.printStackTrace();```输出的信息都为
>java.lang.Exception
	at exception.Rethrowing.f3(Rethrowing.java:42)
	at exception.Rethrowing.f2(Rethrowing.java:34)
	at exception.Rethrowing.f1(Rethrowing.java:24)
	at exception.Rethrowing.main(Rethrowing.java:16)

但是注释掉f1方法中e.fillInStackTrace();则f2中```e.printStackTrace();```输出的信息为
>java.lang.Exception
	at exception.Rethrowing.f3(Rethrowing.java:42)
	at exception.Rethrowing.f2(Rethrowing.java:34)
	at exception.Rethrowing.f1(Rethrowing.java:24)
	at exception.Rethrowing.main(Rethrowing.java:16)

    因为f2方法中```e.printStackTrace();```此时e中的栈轨迹并没有被fillInStackTrace()方法清空因此它的调用链是完整的    

但是main方法好f1方法中的```e.printStackTrace();```输出的信息都为
>java.lang.Exception
	at exception.Rethrowing.f2(Rethrowing.java:37)
	at exception.Rethrowing.f1(Rethrowing.java:24)
	at exception.Rethrowing.main(Rethrowing.java:16)

    因为在f2方法中标准输出后调用了```e.fillInStackTrace();```清空此前栈信息并在此刻重新生成栈轨迹；

### 在finally中使用return和throw
1. 在finally中使用return，则调用者认为方法返回正常，抑制异常的冒泡传输。并且会覆盖try-catch中的return

2. 在finally中使用throw，则会覆盖try-catch中的throw



一个完整的支持嵌套的checked异常类源码如下。我们在这里暂且把它叫做NestedException

```java
public NestedException extends Exception{    
private Throwable cause;    
public NestedException (String msg){    
 super(msg);    
}    

public NestedException(String msg, Throwable ex){    
 super(msg);    
 This.cause = ex;    
}    

public Throwable getCause(){    
 return (this.cause == null ? this :this.cause);    
}    

public getMessage(){    
 String message = super.getMessage();    
 Throwable cause = getCause();    
   if(cause != null){    
     message = message + “;nested Exception is ” + cause;    
   }    
 return message;    
}    
public void printStackTrace(PrintStream ps){    
 if(getCause == null){    
    super.printStackTrace(ps);    

 }else{    
 ps.println(this);    
 getCause().printStackTrace(ps);    
 }    
}    

public void printStackTrace(PrintWrite pw){    
 if(getCause() == null){    
    super.printStackTrace(pw);    
 }    
 else{    
    pw.println(this);    
    getCause().printStackTrace(pw);    
 }    
}    
public void printStackTrace(){    
 printStackTrace(System.error);    
}    
}
```   

同样要设计一个unChecked异常类也与上面一样。只是需要继承RuntimeException。

### 总结   
先说几个知识点
    编程错误异常：空指针或者数组越界以及不合法参数等可以通过代码检查后规避的错误，并且客户端无法采取有效措施    客户端代码异常：
    客户端代码异常：和界面打交道(controller等)调用api不允许的操作，例如传递xml文件格式错误，则返给界面xml解析错误的位置，由客户端可以通过其采用一些替代方法再重新执行。
    资源失效异常：内存不足或网络连接等问题

    检查异常：io异常，sql异常等，jvm要求必须处理
    运行异常：空指针，类型转换，数组越界，非法参数等，jvm不强制要求处理


1.当腰抛出异常时，考虑"如果这种异常一旦抛出，客户端会进行怎么样的处理"如果客户端能够采取措施并规避bug则抛出检查异常强制客户端代码处理错误。比如xml解析失败则抛出检查异常。
1.1 如果触发异常的行为由客户端操作失误或者客户端程序参数什么的错误，也就是客户端代码异常则抛出检查异常
2.保护封装性：不要讲数据库访问层的sql异常传递到业务层，因为业务层不关心SQL异常，此时：
2.1：如果需要客户端代码从异常中恢复则将SQL异常转化为另一个业务层关心的异常，例如SQL错误你需要数据回滚则抛出检查异常
2.2：如果客户端代码无法对其处理则将抛出运行异常runtimeException()
3.当无法提供更有用的信息时不要自定义异常，会增加代码内存消耗并难以读懂
4.不要忽略异常：如果方法抛出检查异常他在提醒你应当采取一些措施而并非trycatch简单捕获记录日志。如果检查异常毫无意义则变为运行异常重新抛出
5.不要捕获顶层异常例如Exception因为有可能会捕获运行异常
